import Head from "next/head";
import Link from "next/link";
import styles from "../../../styles/getStakeholder.module.css";
import React, { Component } from "react";
import NameCard from "../../../components/card/index";
import Header from "../../../components/header/index";
import HomeButton from "../../../components/homeButton";
import product from "../../../ethereum/product";
import { useState, useEffect } from "react";
import web3 from "../../../ethereum/web3";

class Admin extends Component {
  formSubmit = async (e) => {
    e.preventDefault();
    try {
      const accounts = await web3.eth.getAccounts();
      console.log("Waiting for transaction");

      const pid = e.target[0].value;
      const name = e.target[1].value;
      const supply = e.target[2].value;
      const location = e.target[3].value;
      const temperature = e.target[4].value;

      const reqQuantity = await product.methods.getProductQuantity(pid).call({
        from: accounts[0],
      });

      if (parseInt(supply) > reqQuantity) {
        alert("Required quantity is less than the supply.");
      } else {
        await product.methods
          .addStakeholderToProduct(pid, name, supply, location, temperature)
          .send({
            from: accounts[0],
          });

        e.target[0].value = "";
        e.target[1].value = "";
        e.target[2].value = "";
        e.target[3].value = "";
        e.target[4].value = "";

        alert("Stakeholder added to product Successfully");
      }
    } catch (err) {
      alert(err);
    }
  };

  render() {
    return (
      <>
        <Head>
          <title>Milk Supply</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.navBar}>
          <Header title="Add Stakeholder" />
          <Link href="/">
            <a>
              <HomeButton />
            </a>
          </Link>
        </div>
        <div className={styles.formCardContainer}>
          <div className={styles.formCard}>
            <form name="Add Stakeholder" onSubmit={this.formSubmit}>
              <div className={styles.formTile}>
                <label className={styles.formTitle}>Product Id: </label>
                <input
                  className={styles.formInput}
                  name="pid"
                  type="text"
                ></input>
              </div>
              <div className={styles.formTile}>
                <label className={styles.formTitle}>Name: </label>
                <input
                  className={styles.formInput}
                  name="name"
                  type="text"
                ></input>
              </div>
              <div className={styles.formTile}>
                <label className={styles.formTitle}>Supply: </label>
                <input
                  className={styles.formInput}
                  name="suppy"
                  type="text"
                ></input>
              </div>
              <div className={styles.formTile}>
                <label className={styles.formTitle}>Location: </label>
                <input
                  className={styles.formInput}
                  name="location"
                  type="text"
                ></input>
              </div>
              <div className={styles.formTile}>
                <label className={styles.formTitle}>Temperature: </label>
                <input
                  className={styles.formInput}
                  name="temperature"
                  type="text"
                ></input>
              </div>
              <div className={styles.formButtonContainer}>
                <button className={styles.formSubmitButton}>
                  Add Stakeholder
                </button>
              </div>
            </form>
          </div>
        </div>
      </>
    );
  }
}

export default Admin;
