import Head from 'next/head'
import Link from 'next/link';
import styles from '../../../styles/Home.module.css'
import * as React from 'react';
import NameCard  from '../../../components/card/index'
import Header from '../../../components/header/index'
import HomeButton from '../../../components/homeButton';


export default function Admin() {
    return (
      <>
        <Head>
          <title>Milk Supply</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.navBar}>
            <Header title="Product"/>
            <Link href='/'>
                <a>
                <HomeButton />
                </a>
            </Link>
        </div>
        <div className={styles.CardContainer}>
          <div className={styles.homeContentCards}>
            <Link href=''>
              <NameCard title="Register" />
            </Link>
            <Link href=''>
              <NameCard title="Update" />
            </Link>
            <Link href=''>
              <NameCard title="Status" />
            </Link>
          </div> 
        </div>
      </>
    );
}
