import Head from "next/head";
import Link from "next/link";
import styles from "../../../styles/Home.module.css";
import * as React from "react";
import NameCard from "../../../components/card/index";
import Header from "../../../components/header/index";
import HomeButton from "../../../components/homeButton";

export default function Admin() {
  return (
    <>
      <Head>
        <title>Milk Supply</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navBar}>
        <Header title="Product" />
        <Link href="/">
          <a>
            <HomeButton />
          </a>
        </Link>
      </div>
      <div className={styles.CardContainer}>
        <div className={styles.homeContentCards}>
          <Link href="">
            <a>
              <NameCard title="Register" />
            </a>
          </Link>
          <Link href="">
            <a>
              <NameCard title="Update" />
            </a>
          </Link>
          <Link href="/status">
            <a>
              <NameCard title="Status" />
            </a>
          </Link>
        </div>
      </div>
    </>
  );
}
