import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import React, { Component } from "react";
import NameCard from "../../components/card/index";
import Header from "../../components/header/index";
import HomeButton from "../../components/homeButton";
import product from "../../ethereum/product";
import { useState, useEffect } from "react";
import web3 from '../../ethereum/web3';

class Admin extends Component {

  render() {
    return (
      <>
        <Head>
          <title>Milk Supply</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.navBar}>
          <Header title="Product" />
          <Link href="/">
            <a>
              <HomeButton />
            </a>
          </Link>
        </div>
        <div className={styles.CardContainer}>
          <div className={styles.homeContentCards}>
            <Link href="/admin/addProduct">
              <a>
                <NameCard title="Add Product" />
              </a>
            </Link>
            <Link href="/admin/addStakeholder">
              <a>
                <NameCard title="Add Stakeholder" />
              </a>
            </Link>
            <Link href="/status">
              <a>
                <NameCard title="Status" />
              </a>
            </Link>
          </div>
        </div>
      </>
    );
  }
}

export default Admin;
