import Head from "next/head";
import Link from "next/link";
import styles from "../../../styles/Home.module.css";
import React, { Component } from "react";
import NameCard from "../../../components/card/index";
import Header from "../../../components/header/index";
import HomeButton from "../../../components/homeButton";
import product from "../../../ethereum/product";
import { useState, useEffect } from "react";
import web3 from "../../../ethereum/web3";

class Admin extends Component {
  // async componentDidMount(){
  //     const accounts = await web3.eth.getAccounts();
  //     const quantity = await product.methods.getProductQuantity("4").call({
  //         from: accounts[0]
  //     });

  //     console.log(quantity)
  // }

  formSubmit = async (e) => {
    e.preventDefault();
    try {
      const accounts = await web3.eth.getAccounts();
      console.log("Waiting for transaction");

      const name = e.target[0].value;
      const quantity = e.target[1].value;
      const gid = e.target[2].value;

      await product.methods.addProduct(name, quantity, gid).send({
        from: accounts[0],
      });

      e.target[0].value = "";
      e.target[1].value = "";
      e.target[2].value = "";

      alert("Product Added Successfully");
    } catch (err) {
      alert(err);
    }
  };

  render() {
    return (
      <>
        <Head>
          <title>Milk Supply</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.navBar}>
          <Header title="Add Product" />
          <Link href="/">
            <a>
              <HomeButton />
            </a>
          </Link>
        </div>
        <div className={styles.formCardContainer}>
          <div className={styles.formCard}>
            <form name="Add Product" onSubmit={this.formSubmit}>
              <div className={styles.formTile}>
                <label className={styles.formTitle}>Name: </label>
                <input
                  className={styles.formInput}
                  name="name"
                  type="text"
                ></input>
              </div>
              <div className={styles.formTile}>
                <label className={styles.formTitle}>Quantity: </label>
                <input
                  className={styles.formInput}
                  name="quantity"
                  type="text"
                ></input>
              </div>
              <div className={styles.formTile}>
                <label className={styles.formTitle}>Global Id: </label>
                <input
                  className={styles.formInput}
                  name="gid"
                  type="text"
                ></input>
              </div>
              <div className={styles.formButtonContainer}>
                <button className={styles.formSubmitButton}>Add Product</button>
              </div>
            </form>
          </div>
        </div>
      </>
    );
  }
}

export default Admin;
